# Generated by Django 5.0 on 2025-04-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, unique=True, verbose_name='Paca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('km', models.IntegerField(verbose_name='Km')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de despesa')),
            ],
            options={
                'verbose_name': 'Tipo de despesa',
                'verbose_name_plural': 'Tipos de despesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('qnt', models.FloatField(verbose_name='Quantidade')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.car', verbose_name='Carro')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.citys', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_initial', models.IntegerField(verbose_name='Km inicial')),
                ('km_final', models.IntegerField(verbose_name='Km final')),
                ('km_wheeled', models.IntegerField(verbose_name='Km rodado')),
                ('averange', models.FloatField(verbose_name='Média')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='expenses.expense', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'ordering': ['expense'],
            },
        ),
        migrations.CreateModel(
            name='Tryp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da viagem')),
                ('date_initial', models.DateField(verbose_name='Data inicial')),
                ('date_final', models.DateField(verbose_name='Data final')),
                ('user', models.CharField(max_length=50, verbose_name='Usuário')),
                ('km_total', models.IntegerField(verbose_name='Km total')),
                ('atctive', models.BooleanField(default=True, verbose_name='Ativo')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.car', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['date_initial'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.tryp', verbose_name='Viagem'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.typeexpense', verbose_name='Tipo de despesa'),
        ),
    ]
